### ISSUE TITLE
ethereumjs t8n fill compatibility

### ISSUE THREAD

**Issue by winsvega** [ethereum/execution-spec-tests#883] opened 2024-10-08 12:27 UTC
```
test_valid_blob_tx_combinations[fork_Cancun-blockchain_test-blobs_per_tx_(1, 1, 1, 3)] ______________________________________________
[gw2] linux -- Python 3.12.3 /home/wins/Ethereum/execution-spec-tests/.venv/bin/python3
tests/cancun/eip4844_blobs/test_blob_txs.py:604: in test_valid_blob_tx_combinations
    blockchain_test(
src/pytest_plugins/filler/filler.py:805: in __init__
    fixture = self.generate(
src/ethereum_test_specs/blockchain.py:750: in generate
    return self.make_fixture(t8n, fork, eips)
src/ethereum_test_specs/blockchain.py:568: in make_fixture
    header, txs, requests, new_alloc, new_env = self.generate_block_data(
src/ethereum_test_specs/blockchain.py:488: in generate_block_data
    block.header_verify.verify(header)
src/ethereum_test_specs/blockchain.py:212: in verify
    assert value == baseline_value, (
E   AssertionError: invalid header field (excess_blob_gas) value, got 0x00, want 0xe0000
E   assert 0 == 917504

```

not sure if its our side or theirs. the tool seem not be able to parse the input.
pyspecs branch exception_mapper 
```
uv run fill --evm-bin=ethereumjs-t8n "tests/cancun/eip4844_blobs/test_blob_txs.py::test_valid_blob_tx_combinations[fork_Cancun-blockchain_test-blobs_per_tx_(1, 1, 1, 1, 1, 1)]"
```

**Comment by jochem-brouwer** [comment] 2024-10-08 13:39
The problem is on our side and is fixed by: https://github.com/ethereumjs/ethereumjs-monorepo/pull/3728

(At least, this specific test)

**Comment by jochem-brouwer** [comment] 2024-10-08 23:30
We merged the fix, I think this issue could be closed :)

**Comment by raxhvl** [comment] 2024-12-04 06:20
I have tested this and can confirm this issue could be closed.

```console
uv run fill --evm-bin=../ethereumjs-monorepo/packages/vm/test/t8n/ethereumjs-t8ntool.sh  "tests/cancun/eip4844_blobs/test_blob_txs.py::test_valid_blob_tx_combinations[fork_Cancun-blockchain_test-blobs_per_tx_(1, 1, 1, 1, 1, 1)]"

=============== test session starts ================
platform linux -- Python 3.12.6, pytest-7.4.4, pluggy-1.5.0
Generating fixtures for: Frontier, Homestead, Byzantium, Constantinople, ConstantinopleFix, Istanbul, Berlin, London, Paris, Shanghai, Cancun
ethereumjs t8n v1
solc: 0.8.24

tests/cancun/eip4844_blobs/test_blob_txs.py .                [1/1]

--------- Generated html report: <path>/report_fill.html ---------
======  No tests executed - the test fixtures in "fixtures/" may now be executed against a client  ======  

=== 1 passed, 1 deselected, 1 warning in 12.26s ===
```

cc: @danceratopz

**Comment by danceratopz** [comment] 2024-12-04 10:24
Thanks a lot for checking and flagging @raxhvl!

**Closed by danceratopz** 2024-12-04 10:24 UTC
Labels: t8ntools
